<accountPopup@Popup>:
    auto_dismiss: True
    title: "Account"
    size_hint: None, None
    size: 400, 400
    AccountPopupContent:

<AccountPopupContent>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    Label:
        text: "This is your Account-Site. Here, you can set up your Profile Picture, your name and more."
        size_hint: 1, 0.1
        background_normal: ""
        color: 0.18, 0.65, 0.83, 1
